import Head from "next/head";
import DonationForm from "../components/DonationForm";
import PrevDonations from "../components/PrevDonations";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center gap-20 my-6">
        <PrevDonations />
        <DonationForm />
      </main>
    </>
  );
}
